blueprint:
  name: Area Active Template Sensor
  description: >
    Creates a template sensor that turns on if **any** device in the chosen area reports one of your specified "on" states.
  domain: template
  input:
    area:
      name: Area to monitor
      description: Pick the Home Assistant area whose devices you want to watch.
      selector:
        area: {}
    on_states:
      name: States considered "on"
      description: A comma-separated list of states that should set the sensor to on.
      default: on,open,home
      selector:
        text: {}
    sensor_unique_id:
      name: Sensor Unique ID
      description: A unique identifier (e.g. "living_room_active").
      selector:
        text: {}
    sensor_name:
      name: Sensor Name
      description: The name of the sensor to create.
      selector:
        text: {}

variables:
  area: !input area
  on_states: !input on_states.split(',')
  sensor_unique_id: !input sensor_unique_id
  sensor_name: !input sensor_name

binary_sensor:
  name: {{ sensor_name }}
  unique_id: {{ sensor_unique_id }}
  state: >
    {% set area_id = area_registry.get_area(area).name %}
    {% set devices = area_entities(area_id) %}
    {% set active_states = on_states.split(',') %}
    {% if expand(devices) | selectattr('state', 'in', active_states) | list | count > 0 %}
      on
    {% else %}
      off
    {% endif %}
  attributes:
    active_devices: >
      {% set active_states = on_states.split(',') %}
      {{ expand(devices) | selectattr('state', 'in', active_states) | map(attribute='entity_id') | list | join(', ') }}
