blueprint:
  name: Area Active Template Sensor
  description: A template sensor that turns on if **any** device in the chosen area reports one of your specified "on" states.
  domain: template
  input:
    area:
      name: Area to monitor
      description: Pick the Home Assistant area whose devices you want to watch.
      selector:
        area: {}
    on_states:
      name: States considered "on"
      description: A comma-separated list of states that should set the sensor to on.
      default: on,open,home
      selector:
        text: {}

variables:
  area_name: !input area
  on_states: !input on_states

binary_sensor:
  state: >
    {% set device_list = area_entities(area_name) %}
    {% set active_states = on_states.split(',') %}
    {% if expand(device_list) | selectattr('state', 'in', active_states) | list | count > 0 %}
      on
    {% else %}
      off
    {% endif %}
  attributes:
    active_devices: >
      {% set device_list = area_entities(area_name) %}
      {% set active_states = on_states.split(',') %}
      {{ expand(device_list) | selectattr('state', 'in', active_states) | map(attribute='entity_id') | list | join(', ') }}
