blueprint:
  name: Area Active Template Sensor
  description: A template sensor that turns on if **any** device in the chosen area reports one of your specified "on" states.
  domain: template
  input:
    area:
      name: Area to monitor
      description: Pick the Home Assistant area whose devices you want to watch.
      selector:
        area: {}
    on_states:
      name: States considered "on"
      description: A comma-separated list of states that should set the sensor to on.
      default: on,open,home
      selector:
        text: {}

binary_sensor:
  state: >
    {% set area_id = area_registry.get_area(!input area).name %}
    {% set devices = area_entities(area_id) %}
    {% set active_states = !input on_states.split(',') %}
    {% if expand(devices) | selectattr('state', 'in', active_states) | list | count > 0 %}
      on
    {% else %}
      off
    {% endif %}
  attributes:
    active_devices: >
      {% set active_states = !input on_states.split(',') %}
      {{ expand(devices) | selectattr('state', 'in', active_states) | map(attribute='entity_id') | list | join(', ') }}
