blueprint:
  name: Basic Template Sensor
  description: Create a template sensor from your inputs
  domain: template
  input:
    sensor_name:
      name: Sensor Name
      selector:
        text: {}
    state_template:
      name: State Template
      selector:
        template: {}

template:
  sensor:
    - name: !input sensor_name
      state: >-
        {{ !input state_template }}
