blueprint:
  name: Simple State Change Notifier
  description: >
    Triggers when the chosen entity changes state and sends a notification.
  domain: automation
  input:
    monitored_entity:
      name: Entity to Monitor
      selector:
        entity:
          domain: sensor
    notify_service:
      name: Notification Service
      selector:
        action: []
        
trigger:
  - platform: state
    entity_id: !input monitored_entity

action:
  - service: !input notify_service
    data:
      message: >
        "{{ monitored_entity }} changed to {{ trigger.to_state.state }}"
