blueprint:
  name: Area Turn Off
  description: Blueprint of domain script to turn off all devices in a selected Home Assistant area.
  source_url: https://github.com/craiglemon/blueprints/blob/master/script/area_turn_off.yaml
  domain: script
  input:
    area:
      name: Area to Shutdown
      description: Select the Home Assistant Area whose devices you want to turn off.
      selector:
        area: {}
    primary_domains:
      name: Primary domains to Turn Off
      description: >
        Comma-separated list of primary domains (e.g. 'switch,light,fan,media_player').
      default: switch,light,fan,media_player
      selector:
        text: {}
    exclude_entities:
      name: Entities to exclude
      description: An array of entity IDs to ignore.
      default: []
      selector:
        entity:
          multiple: true
    retry_count: 
      name: Retry count
      description: Number of times to retry turning off devices if they fail.
      default: 3
      selector:
        number: {}
    retry_delay:
      name: Retry delay
      description: Delay in seconds between retries.
      default: 5
      selector:
        number: {}
    on_states:
      name: On States
      description: Comma-separated list of states that indicate a device is "on".
      default: 'on,playing,home,open'
      selector:
        text: {}
    notify_service:
      name: Notification Service
      description: Optional notify service to alert if devices remain on.
      default: null
      selector:
        entity:
          domain: notify
      
mode: single

sequence:
  - variables:
      primary_domains_list: "{{ input.primary_domains.split(',') | map('trim') | list }}"
      on_states_list: "{{ input.on_states.split(',') | map('trim') | list }}"

      # Get all the entities in the room, then filter by `domain in input.primary_domains` and `entity_id not in input.exclude_list`
      primary_entities: |-
        {{ 
          (expand(area_entities(input.area)) |
            rejectattr('entity_id','in',input.exclude_entities | default([])) | 
            selectattr('domain','in',primary_domains_list) | 
            map(attribute='entity_id') | 
            list) | default([])
        }}
      # Get all the entities in the room, then filter by `domain equalto climate` and `entity_id not in input.exclude_list`
      climate_entities: |-
        {{ 
          (expand(area_entities(input.area)) |
            rejectattr('entity_id','in',input.exclude_entities | default([])) | 
            selectattr('domain','in',['climate']) | 
            map(attribute='entity_id') | 
            list) | default([])
        }}
      # Get all the entities in the room, then filter by `domain equalto cover` and `entity_id not in input.exclude_list`
      cover_entities: |-
        {{ 
          (expand(area_entities(input.area)) |
            rejectattr('entity_id','in',input.exclude_entities | default([])) | 
            selectattr('domain','in',['cover']) | 
            map(attribute='entity_id') | 
            list) | default([])
        }}
  # 1. Turn Off Primary devices
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ primary_entities | length > 0 }}"
      sequence:
        - service: homeassistant.turn_off
          target:
            entity_id: "{{ primary_entities }}"
  # 2. Turn Off Climate devices
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ climate_entities | length > 0 }}"
      sequence:
        - service: climate.set_hvac_mode
          target:
            entity_id: "{{ climate_entities }}"
          data:
            hvac_mode: 'off'
  # 3. Close Covers
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ cover_entities | length > 0 }}"
      sequence:
        - service: cover.close_cover
          target:
            entity_id: "{{ cover_entities }}"
  # 4. Retry any entities that are still "on"
  - repeat:
      count: "{{ input.retry_count | int }}"
      sequence:
        - delay:
            seconds: "{{ input.retry_delay | int }}"
        - variables:
            still_on_entities: |-
              {{ 
                expand(area_entities(input.area)) |
                  rejectattr('entity_id','in',input.exclude_entities | default([])) | 
                  selectattr('state','in',on_states_list) |
                  selectattr('domain','in',primary_domains_list) | 
                  map(attribute='entity_id') |
                  list 
              }}
        - choose:
            - conditions:
                - condition: template
                  value_template: "{{ still_on_entities | length > 0 }}"
              sequence:
                - service: homeassistant.turn_off
                  target:
                    entity_id: "{{ still_on_entities }}"
  # 5. Final log message
  - variables:
      final_still_on_entities: |-
        {{ 
          expand(area_entities(input.area)) |
            rejectattr('entity_id','in',input.exclude_entities | default([])) | 
            selectattr('state','in',on_states_list) |
            selectattr('domain','in',primary_domains_list) | 
            map(attribute='entity_id') |
            list 
        }}
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ final_still_on_entities | length > 0 and input.notify_service is not none }}"
        sequence:
          - service: "{{ input.notify_service }}"
            data:
              message: >
                Devices still on in area [{{ input.area }}]:  {{ final_still_on_entities | join(', ') }}
