blueprint:
  name: Area Turn Off
  description: >
    Blueprint of domain script to turn off all devices in a selected Home Assistant area.
  domain: script
  input:
    area:
      name: Area to Shutdown
      description: Select the Home Assistant Area whose devices you want to turn off.
      selector:
        area: {}
    primary_domains:
      name: Primary domains to Turn Off
      description: >
        Comma-separated list of primary domains (e.g. 'switch,light,fan,media_player').
      default: switch,light,fan,media_player
      selector:
        text: {}
    exclude_entities:
      name: Entities to exclude
      description: An array of entity IDs to ignore.
      selector:
        entity:
          multiple: true

mode: single

variables:
  input_area: !input area
  input_primary_domains: !input primary_domains
  input_exclude_entities: !input exclude_entities

sequence:
  - variables:
      # Get all the entities in the room, then filter by domain and exclude list
      # Run the following Home Assistant -> Developer Tools -> Template to determine what entities require excluding

      # {% set input_area = 'Lounge' %}
      # {% set input_exclude_entities = [ ] %}
      # {% set input_primary_domains = 'switch,light,fan,media_player' %}
      # {% set area_entities = expand(area_entities(input_area)) | rejectattr('entity_id','in',input_exclude_entities) | list %}
      # primary_entities: {{ area_entities | selectattr('domain','in', input_primary_domains.split(',') | map('trim') | list) | map(attribute='entity_id') | sort | list}}
      # climate_entities: {{ area_entities | selectattr('domain','equalto','climate') | map(attribute='entity_id') | sort | list }}
      # cover_entities: {{ area_entities | selectattr('domain','equalto','cover') | map(attribute='entity_id') | sort | list }}

      primary_entities: |-
        {{ 
          expand(area_entities(input_area)) |
            rejectattr('entity_id','in',input_exclude_entities) | 
            selectattr('domain','in',input_primary_domains.split(',') | map('trim') | list) | 
            map(attribute='entity_id') | 
            list 
        }}
      climate_entities: |-
        {{ 
          expand(area_entities(input_area)) |
            selectattr('domain','equalto','climate') | 
            map(attribute='entity_id') | 
            list 
        }}
      cover_entities: |-
        {{ 
          expand(area_entities(input_area)) |
            selectattr('domain','equalto','cover') | 
            map(attribute='entity_id') | 
            list 
        }}
      
  - service: persistent_notification.create
    data:
      title: "primary_entities"
      message: "{{ primary_entities }}"

  # 1. Turn Off Primary devices
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ primary_entities | length > 0 }}"
      sequence:
        - service: homeassistant.turn_off
          data:
            entity_id: >
              {{ primary_entities }}

  # 2. Turn Off Climate devices
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ climate_entities | length > 0 }}"
      sequence:
        - service: climate.set_hvac_mode
          target:
            entity_id: "{{ climate_entities }}"
          data:
            hvac_mode: 'off'

  # 3. Close Covers
  - choose:
    - conditions: 
        - condition: template
          value_template: "{{ cover_entities | length > 0 }}"
      sequence:
        - service: cover.close_cover
          data:
            entity_id: >
              {{ cover_entities }}
              
  # - variables:
  #     device_list: >
  #       {{ area_entities(input_area) | reject('in',input_exclude_entities) | list }}
  #     cover_list: >
  #       {{ expand(device_list) | selectattr('domain','equalto','cover') | map(attribute='entity_id') | list }}
  #     climate_list: >
  #       {{ expand(device_list) | selectattr('domain','equalto','climate') | map(attribute='entity_id') | list }}
  # # 1. Turn Off Primary Domains
  # - action: homeassistant.turn_off
  #   data:
  #     entity_id: >
  #       {% set domains = input_domains.split(',') %}  
  #       {{ expand(device_list) | selectattr('domain','in',domains) | map(attribute='entity_id') | list | join(',') }}
  # # # 2. Close Covers
  # # - action: cover.close_cover
  # #   data:
  # #     entity_id: >
  # #       {{ cover_list | join(',') }}
  # # 3. Turn Off Climate Devices
  # - action: 
  #     - choose:
  #         - conditions: 
  #             - condition: Template
  #               value_template: "{{ climate_list | length > 0 }}"
  #           sequence:
  #             - service: climate.set_hvac_mode
  #               data:
  #                 hvac_mode: 'off'
  #               target:
  #                 entity_id: "{{ climate_list }}"
  # # # 4. Retry Loop for Remaining Entities
  # # - repeat:
  # #     count: !input retry_count
  # #     sequence:
  # #       - delay: seconds: !input retry_delay
  # #       - variables:
  # #           still_on: >-
  # #             {{ expand('area.' ~ !input area)
  # #                | rejectattr('state','equalto','off')
  # #                | selectattr('domain','in', (!input domains).split(',') | map('trim') | list)
  # #                | map(attribute='entity_id')
  # #                | list }}
  # #       - choose:
  # #           - conditions: "{{ still_on | length > 0 }}"
  # #             sequence:
  # #               - service: homeassistant.turn_off
  # #                 data:
  # #                   entity_id: "{{ still_on | join(',') }}"
  # # # 5. Final Notification
  # # - variables:
  # #     final_still_on: >-
  # #       {{ expand('area.' ~ !input area)
  # #          | rejectattr('state','equalto','off')
  # #          | selectattr('domain','in', (!input domains).split(',') | map('trim') | list)
  # #          | map(attribute='entity_id')
  # #          | list }}
  # # - choose:
  # #     - conditions:
  # #         - "{{ final_still_on | length > 0 }}"
  # #         - "{{ !input notify_service != 'none' }}"
  # #       sequence:
  # #         - service: !input notify_service
  # #           data:
  # #             message: >
  # #               Devices still on in area {{ !input area }}: 
  # #               {{ final_still_on | join(', ') }}


